name: Docker CI Pipeline
run-name: ${{ github.actor }} is running Docker CI Pipeline 🚀
on: [push]
jobs:
  docker-ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download 24hrs Old Logs
        uses: pawanbahuguna/action-logs/@v1.0.1
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
      - name: list files
        run: ls -lrt
        
      - name: list files in jobs-log
        run: ls -lrt jobs-log
        
      - name: view content
        run: cat $(ls jobs-log | head -n 1 | sed 's|^|jobs-log/|')

      - name: Trigger Target Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/target-workflow.yml/dispatches \
            -d '{"ref":"main"}'
